import type { GmailReadPolicy } from "../../settings";

export interface EmailShape {
  id: string;
  from: string;
  subject: string;
  snippet: string;
  body?: string;
  hasAttachments: boolean;
  labels: string[];
}

export interface PolicyVerdict {
  action: "read" | "summarize_only" | "skip";
  reasons: string[];
  redactions: RedactionHit[];
}

export interface RedactionHit {
  field: "subject" | "snippet" | "body";
  match: string;
  category: "otp" | "auth_code" | "finance" | "private_attachment" | "sender_block" | "subject_deny";
}

const OTP_RULES: Array<{ rule: RegExp; category: RedactionHit["category"] }> = [
  { rule: /\b(?:otp|one[- ]?time password|verification code|security code)\b[^\n]{0,60}?\b\d{3,8}\b/i, category: "otp" },
  { rule: /\b\d{6}\b\s+is\s+your\s+(?:otp|code|verification)/i, category: "otp" },
  { rule: /code:\s*\d{4,8}\b/i, category: "auth_code" },
  { rule: /(?:account|routing|ifsc|iban)\s*(?:number)?\s*[:#]?\s*[a-z0-9 ]{6,}/i, category: "finance" },
  { rule: /\bcvv\b\s*[:#]?\s*\d{3,4}/i, category: "finance" },
  { rule: /(?:aadhaar|pan)\s*(?:number)?\s*[:#]?\s*[a-z0-9]{8,}/i, category: "finance" }
];

/**
 * Photon NEVER reads private mail content wholesale. Every email is passed
 * through this policy before any summary is generated by an LLM. The guiding
 * idea: the agent can know "something arrived from your bank", but must never
 * paraphrase the one-time password inside it.
 */
export function judgeEmail(email: EmailShape, policy: GmailReadPolicy): PolicyVerdict {
  const reasons: string[] = [];

  if (policy.blockSenders.some((pattern) => matches(email.from, pattern))) {
    return { action: "skip", reasons: [`sender matches block list: ${email.from}`], redactions: [] };
  }

  if (policy.allowSenders.length > 0 && !policy.allowSenders.some((pattern) => matches(email.from, pattern))) {
    return { action: "skip", reasons: [`sender not in allow list: ${email.from}`], redactions: [] };
  }

  const redactions: RedactionHit[] = [];
  for (const field of ["subject", "snippet", "body"] as const) {
    const text = email[field] ?? "";
    if (!text) continue;
    for (const { rule, category } of OTP_RULES) {
      const match = rule.exec(text);
      if (!match) continue;
      if (category === "otp" && !policy.redactOtp) continue;
      if (category === "auth_code" && !policy.redactAuthCodes) continue;
      if (category === "finance" && !policy.redactFinance) continue;
      redactions.push({ field, match: match[0], category });
    }
  }

  for (const pattern of policy.subjectDenyPatterns) {
    if (new RegExp(pattern, "i").test(email.subject)) {
      redactions.push({ field: "subject", match: pattern, category: "subject_deny" });
    }
  }

  if (policy.redactPrivateAttachments && email.hasAttachments) {
    reasons.push("has attachments - body content withheld, only metadata allowed");
    redactions.push({ field: "body", match: "[attachment_withheld]", category: "private_attachment" });
  }

  if (redactions.length > 0) {
    return {
      action: "summarize_only",
      reasons: [...reasons, `${redactions.length} redactions applied`],
      redactions
    };
  }

  return { action: "read", reasons, redactions: [] };
}

/**
 * Apply the verdict to the email, returning a safe-to-LLM projection.
 */
export function redactEmail(email: EmailShape, verdict: PolicyVerdict): EmailShape {
  if (verdict.action === "skip") {
    return { ...email, subject: "[skipped by policy]", snippet: "", body: "" };
  }
  if (verdict.action === "read") return email;

  let subject = email.subject;
  let snippet = email.snippet;
  let body = email.body ?? "";

  for (const hit of verdict.redactions) {
    if (hit.field === "subject") subject = subject.replaceAll(hit.match, "[redacted]");
    if (hit.field === "snippet") snippet = snippet.replaceAll(hit.match, "[redacted]");
    if (hit.field === "body") body = body.replaceAll(hit.match, "[redacted]");
  }

  if (verdict.redactions.some((hit) => hit.category === "private_attachment")) {
    body = "[body withheld by policy]";
  }

  return { ...email, subject, snippet, body };
}

function matches(field: string, pattern: string): boolean {
  if (!pattern) return false;
  if (pattern.startsWith("/") && pattern.endsWith("/")) {
    return new RegExp(pattern.slice(1, -1), "i").test(field);
  }
  return field.toLowerCase().includes(pattern.toLowerCase());
}
